### PR TITLE
fix webstorm jettison dependency

### PR DESCRIPTION
**Pull request by mabab**
1. Fix webstorm dependency on jettison
2. upgrade gradle to last version

https://github.com/patricklx/intellij-emberjs-experimental/issues/30

### CODE REVIEW

**Comment by patricklx** [comment]
thanks for the fix.
But you have ti revert the gradle upgrade. It somehow makes the tests fail.

**Comment by mabab** [comment]
> thanks for the fix. But you have ti revert the gradle upgrade. It somehow makes the tests fail.

on main brach I have same failed tests

**Comment by mabab** [comment]
@patricklx gradle will return to the main branch state 🫡

**Comment by patricklx** [comment]
thanks

**Pull request merged**
